export interface InferenceSignals {
  detected_indicators: string[];
  phishing_signals: string[];
  authentication_signals: string[];
  url_indicators: string[];
  urgency_indicators: string[];
}

export interface PredictionResponse {
  model_id: string;
  model_version: string;
  prediction: 'phishing' | 'legitimate' | string;
  probability: number;
  risk_score: number;
  confidence: number;
  threshold_used: number;
  feature_families: string[];
  signals: InferenceSignals;
  recommendations: string[];
  processing_time_ms: number;
  final_classification?: 'safe' | 'suspicious' | 'phishing' | string | null;
  final_risk_score?: number | null;
  final_decision_confidence?: number | null;
  rule_findings?: ThreatSignal[];
  analysis_completeness?: AnalysisCompleteness | null;
  analysis_completeness_status?: 'complete' | 'partial' | 'incomplete' | 'stale' | 'unavailable' | string;
  analysis_freshness?: 'current' | 'stale' | string;
  stale_reason?: string | null;
  missing_evidence?: string[];
  incomplete_reason_codes?: string[];
  decision_safety_status?: 'eligible' | 'needs_review' | 'unable_to_verify' | 'rescan_required' | string;
  presentation_state?: 'safe' | 'suspicious' | 'phishing' | 'needs_review' | 'unable_to_verify' | 'rescan_required' | string;
  requires_rescan?: boolean;
  safe_verdict_allowed?: boolean;
  engines_requested?: string[];
  engines_completed?: string[];
  engines_failed?: string[];
  decision_source?: string;
  fusion_performed?: boolean;
  fallback_used?: boolean;
  fallback_reason?: string | null;
  rule_raw_score?: number | null;
  rule_adjusted_score?: number | null;
  rule_ml_agreement?: string | null;
  fusion_reason?: string | null;
  authentication_evidence_status?: string;
  positive_authentication_evidence?: Array<Record<string, unknown>>;
  extracted_urls?: string[];
  url_evidence?: Array<{ url: string; source_type: string; user_actionable: boolean; external_domain?: boolean | null; security_relevance?: string }>;
  link_language_present?: boolean;
  actual_url_count?: number;
  html_anchor_count?: number;
  url_extraction_status?: string;
  url_extraction_reason?: string | null;
  current_rule_version?: string | null;
  stored_rule_version?: string | null;
  parser_success?: boolean;
  rules_available?: boolean;
  ml_available?: boolean;
  fusion_available?: boolean;
  fusion_policy_version?: string;
  fusion_inputs?: Record<string, unknown>;
  fusion_components?: string[];
  rule_weight?: number;
  ml_weight?: number;
  safety_floor_applied?: boolean;
  safety_floor_rule_id?: string | null;
  applied_floor_reason?: string | null;
  disagreement_resolution?: string | null;
  pre_floor_score?: number | null;
  post_floor_score?: number | null;
  dominant_evidence_source?: string;
  evidence_families?: string[];
  high_confidence_rule_evidence?: boolean;
  protective_evidence?: string[];
  authentication_evidence?: Array<{
    mechanism: string;
    state: string;
    domain?: string | null;
    aligned_with_from?: boolean | null;
    result?: string | null;
    display_label?: string;
    detail?: string | null;
  }>;
  actionable_url_count?: number;
  tracking_pixel_count?: number;
  external_tracking_pixel_count?: number;
  mailto_count?: number;
  actionable_mailto_count?: number;
  mailto_destinations_redacted_or_normalized?: string[];
  mailto_domain_count?: number;
  mailto_external_domain_mismatch?: boolean;
  mailto_personal_provider?: boolean;
  mailto_action_types?: string[];
  mailto_action_type?: string;
}

export interface HealthResponse {
  status: string;
  service: string;
  firebase: string;
  loaded_model: string | null;
  model_version: string | null;
  calibration: string | null;
  deployment_candidate: boolean;
  activated: boolean;
  pipeline_sha: string | null;
  registry_status?: string | null;
}
import type { AnalysisCompleteness, ThreatSignal } from './analysis';
