import type { AnalysisCompletenessState, AnalysisInputMode, EmailAttachmentMetadata, ThreatClassification, ThreatSeverity } from './analysis';

export interface ReportIndicator {
  code: string;
  title: string;
  category: string;
  severity: ThreatSeverity;
  score: number;
  description: string | null;
  evidence: string | null;
  source_engine?: string;
  evidence_type?: string;
  tone?: string;
  contributes_to_score?: boolean;
  provenance?: string | null;
}

export interface ScanReportData {
  report_schema_version: '1.3';
  product: 'PhishShield AI';
  report_generated_at: string;
  scan_id: string;
  scan_timestamp: string;
  subject: string;
  sender: string;
  recipients: string[];
  input_mode: AnalysisInputMode | 'not_recorded';
  final_classification: ThreatClassification;
  risk_score: number;
  confidence: number;
  final_decision_confidence: number | null;
  rule_raw_score: number | null;
  rule_adjusted_score: number | null;
  ml_prediction: string | null;
  ml_phishing_probability: number | null;
  ml_threshold: number | null;
  rule_ml_agreement: string | null;
  fusion_reason: string | null;
  analysis_completeness: AnalysisCompletenessState | 'not_recorded';
  analysis_completeness_status: 'complete' | 'partial' | 'incomplete' | 'stale' | 'unavailable' | 'not_recorded';
  missing_evidence: string[];
  incomplete_reason_codes: string[];
  decision_safety_status: string;
  presentation_state: string;
  requires_rescan: boolean;
  safe_verdict_allowed: boolean;
  engines_requested: string[];
  engines_completed: string[];
  engines_failed: string[];
  decision_source: string;
  fusion_performed: boolean;
  fallback_used: boolean;
  fallback_reason: string | null;
  fusion_policy_version: string;
  fusion_inputs: Record<string, unknown>;
  fusion_components: string[];
  rule_weight: number;
  ml_weight: number;
  safety_floor_applied: boolean;
  safety_floor_rule_id: string | null;
  applied_floor_reason: string | null;
  disagreement_resolution: string | null;
  pre_floor_score: number | null;
  post_floor_score: number | null;
  dominant_evidence_source: string;
  evidence_families: string[];
  high_confidence_rule_evidence: boolean;
  protective_evidence: string[];
  positive_authentication_evidence: Array<{
    mechanism: string;
    state: string;
    domain: string | null;
    aligned_with_from: boolean | null;
    result?: string | null;
    display_label?: string;
    detail?: string | null;
  }>;
  authentication_evidence: Array<{
    mechanism: string;
    state: string;
    domain?: string | null;
    aligned_with_from?: boolean | null;
    result?: string | null;
    display_label?: string;
    detail?: string | null;
  }>;
  authentication_evidence_status: 'available' | 'passed' | 'unavailable' | 'failed' | 'inconclusive';
  url_evidence: Array<{ url: string; source_type: string; user_actionable: boolean; external_domain?: boolean | null; security_relevance?: string }>;
  actionable_url_count: number;
  tracking_pixel_count: number;
  external_tracking_pixel_count: number;
  mailto_count: number;
  actionable_mailto_count: number;
  mailto_destinations_redacted_or_normalized: string[];
  mailto_domain_count: number;
  mailto_external_domain_mismatch: boolean;
  mailto_personal_provider: boolean;
  mailto_action_types: string[];
  mailto_action_type: string;
  analysis_freshness: 'current' | 'stale';
  stale_reason: string | null;
  link_language_present: boolean;
  actual_url_count: number;
  html_anchor_count: number;
  url_extraction_status: string;
  url_extraction_reason: string | null;
  rule_engine: { status: 'active' | 'unknown'; version: string | null };
  ml_engine: { status: 'available' | 'unavailable' | 'unknown'; version: string | null };
  detected_indicators: ReportIndicator[];
  recommendations: string[];
  extracted_urls: string[];
  attachments: EmailAttachmentMetadata[];
  privacy_disclaimer: string;
}
